// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgtESFJouExNH3Xp39WILfk8pqrcFlZAw',
    appId: '1:1000021958499:web:e4e622f778a44226f03d56',
    messagingSenderId: '1000021958499',
    projectId: 'furhouse-app',
    authDomain: 'furhouse-app.firebaseapp.com',
    storageBucket: 'furhouse-app.appspot.com',
    measurementId: 'G-3735CD5WTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2HTtfObeQTFAxBWeRdbDJ6wlxDs_DPJk',
    appId: '1:1000021958499:android:d1d5c919aa23c452f03d56',
    messagingSenderId: '1000021958499',
    projectId: 'furhouse-app',
    storageBucket: 'furhouse-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHrSWWand75nn1N4nT0z2QymSg-58OSDA',
    appId: '1:1000021958499:ios:e5756176217bf950f03d56',
    messagingSenderId: '1000021958499',
    projectId: 'furhouse-app',
    storageBucket: 'furhouse-app.appspot.com',
    iosClientId:
        '1000021958499-o48h980p2ncbsr315bacb42hvfh8mvpn.apps.googleusercontent.com',
    iosBundleId: 'com.example.furhouseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHrSWWand75nn1N4nT0z2QymSg-58OSDA',
    appId: '1:1000021958499:ios:e5756176217bf950f03d56',
    messagingSenderId: '1000021958499',
    projectId: 'furhouse-app',
    storageBucket: 'furhouse-app.appspot.com',
    iosClientId:
        '1000021958499-o48h980p2ncbsr315bacb42hvfh8mvpn.apps.googleusercontent.com',
    iosBundleId: 'com.example.furhouseApp',
  );
}
